/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExportProjectIdRouteImport } from './routes/export.$projectId'
import { Route as EditorProjectIdRouteImport } from './routes/editor.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportProjectIdRoute = ExportProjectIdRouteImport.update({
  id: '/export/$projectId',
  path: '/export/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorProjectIdRoute = EditorProjectIdRouteImport.update({
  id: '/editor/$projectId',
  path: '/editor/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor/$projectId': typeof EditorProjectIdRoute
  '/export/$projectId': typeof ExportProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor/$projectId': typeof EditorProjectIdRoute
  '/export/$projectId': typeof ExportProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editor/$projectId': typeof EditorProjectIdRoute
  '/export/$projectId': typeof ExportProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/editor/$projectId' | '/export/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/editor/$projectId' | '/export/$projectId'
  id: '__root__' | '/' | '/editor/$projectId' | '/export/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorProjectIdRoute: typeof EditorProjectIdRoute
  ExportProjectIdRoute: typeof ExportProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export/$projectId': {
      id: '/export/$projectId'
      path: '/export/$projectId'
      fullPath: '/export/$projectId'
      preLoaderRoute: typeof ExportProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$projectId': {
      id: '/editor/$projectId'
      path: '/editor/$projectId'
      fullPath: '/editor/$projectId'
      preLoaderRoute: typeof EditorProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorProjectIdRoute: EditorProjectIdRoute,
  ExportProjectIdRoute: ExportProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
